plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

title: 'Bleedmagic'
logo: /assets/img/logo.png
description: 'Developer in training focused on web technologies, cybersecurity, and network engineering.'
show_downloads: false
theme: jekyll-theme-minimal

author:
  name: Victor Vasquez
  email: bleedmagic@proton.me

twitter_handle: '@Bleedmagic87'
twitter_url: https://x.com/Bleedmagic87

permalink: /:title
url: https://bleedmagic.github.io/
timezone: Asia/Manila


exclude:
  - README.md
  - LICENSE
