title: 'Victor Vasquez'
logo: ./assets/img/logo.png
description: 'Networking, Security, Web Development'
show_downloads: false
theme: jekyll-theme-minimal

exclude:
  - README.md

url: https://bleedmagic.github.io/

timezone: Asia/Manila
